version: '3.8'
services:
  api-dev:
    build:
      context: ..
      dockerfile: src/Dockerfile
      target: dev
    container_name: api-dev
    environment:
      - FLASK_ENV=development
    ports:
      - "0.0.0.0:5005:5005"

  api-prod:
    build:
      context: ..
      dockerfile: src/Dockerfile
      target: prod
    container_name: api-prod
    environment:
      - FLASK_ENV=production
    ports:
      - "0.0.0.0:5005:5005"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../src/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "0.0.0.0:9090:9090"
    depends_on:
      - api-prod

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "0.0.0.0:3000:3000"
    depends_on:
      - prometheus
    # Optionally mount provisioning/dashboards here
