version: '3.8'
services:
  api-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: api-dev
    environment:
      - FLASK_ENV=development
    ports:
      - "5005:5005"
    volumes:
      - ./src:/app
      - ./model:/model
      - ./data:/data
    command: ["python", "app_development.py"]

  api-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: api-prod
    environment:
      - FLASK_ENV=production
    ports:
      - "5006:5005"
    volumes:
      - ./src:/app
      - ./model:/model
      - ./data:/data
    command: ["python", "app_production.py"]

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-dev
      - api-prod

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./src/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
