# Kubernetes manifest for development
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-dev
  template:
    metadata:
      labels:
        app: api-dev
    spec:
      containers:
      - name: api-dev
        image: api-dev:latest
        ports:
        - containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: api-dev
spec:
  selector:
    app: api-dev
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
