version: '3.8'

services:
  house-price-api:
    build: .
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=production
    volumes:
      - ../data:/app/data
      - ../model:/app/model
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
